name: variables

on:
  workflow_dispatch:

env:
 cloud: Azure cloud  

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      greeting: Hello
    steps:
    - name: "Say Hello honey its Monday"
      run: echo "$greeting $Firstname $cloud
      env:
        Firstname: Anil
